import type { Metadata } from "next";

/** Shared social / OG copy for layout + homepage */
export const SOCIAL_TITLE = "HalalStyle — The Excellence Filter for Modest Fashion";

export const SOCIAL_DESCRIPTION =
  "Curated modest luxury for the modern Muslim high-achiever. 100% Halal-verified fashion, lifestyle and gifts. Ships via Amazon.ca.";

/** Generated by app/opengraph-image.tsx & app/twitter-image.tsx (1200×630) */
export const SOCIAL_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "HalalStyle — Emerald and gold hero, The Excellence Filter for Modest Fashion",
} as const;

export const socialOpenGraph = {
  title: SOCIAL_TITLE,
  description: SOCIAL_DESCRIPTION,
  type: "website" as const,
  siteName: "HalalStyle",
  locale: "en_CA",
  images: [SOCIAL_IMAGE],
};

export const socialTwitter = {
  card: "summary_large_image" as const,
  title: SOCIAL_TITLE,
  description: SOCIAL_DESCRIPTION,
  images: [SOCIAL_IMAGE.url],
};

export function buildHomeMetadata(canonicalUrl: string): Metadata {
  return {
    title: SOCIAL_TITLE,
    description: SOCIAL_DESCRIPTION,
    alternates: { canonical: "/" },
    openGraph: { ...socialOpenGraph, url: canonicalUrl },
    twitter: socialTwitter,
  };
}
